### ISSUE TITLE
It says internet connection not allowed in the console.

### ISSUE THREAD

**Issue by X3Golden** [superyor/BetterSync#9]
What am I doing wrong?
Is it a bug?
![bettersync](https://user-images.githubusercontent.com/26051336/70382501-84452b80-195d-11ea-8cf9-460107b11789.png)

**Comment by superyor** [comment]
Enable "Allow internet connections" and "Allow script/config editing" in the lua script settings.
https://i.imgur.com/gkACdY0.png
